### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by Shellyhan** [jumio-oss/geb-mobile#8]
Hi there,

Thanks very much for sharing the project. I've been looking for a mobile version of Web for long!

I hope you could help to take a look at the issue I encounter. I tried running the appiumOnSauceLabs task (./gradlew -i appiumOnSauceLabs), and got the following error log:

* What went wrong:
14:15:03.864 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not determine the dependencies of task ':appiumOnSauceLabs'.
14:15:03.864 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.lang.NullPointerException (no error message)

So I've had appium and Android SDK installed and it's working fine for my other projects; setup a saucelabs account and have the app in sauce-storage already. I'd appreciate it a lot if you could provide any insights and ideas.

Thank you!

Shelly

**Comment by mueke** [comment]
hi, 
build should work now. i started some refactoring, but in the wrong branch. 
please try it again. 
br georg

**Comment by mueke** [comment]
please use branch master

**Comment by Shellyhan** [comment]
Hi George,

Thanks for the quick reply! I clone the master branch, but still getting the same error. Here are some of me local setup info:
- appium server version is 1.7.1
- running on MacOS
- using saucelabs, have uploaded the sample app to sauce storages
- configured the saucelabs credential

I also tried with an Android device, and still getting the same error. Please let me know if you could like to know any other information. Thank you for helping!


Cheers,

Shelly

**Comment by mueke** [comment]
hi, sorry. 
I totally forgot, that I moved the test-classes into the subfolder structure.
please try

`SAUCE_USERNAME=<your_saucelabs_usernme> SAUCE_ACCESS_KEY=<access_key> ./gradlew -i clean appiumOnTestObjecs`

Let  me know if it worked.
I have no account there anymore so I cannot try the whole thing.

br georg

**Comment by mueke** [comment]
btw, if you are trying the saucelabs example, you don't need the appium....
and as I already mentioned, I cannot guarantee that this works still on saucelabs
if you want to run the test locally:
- connect a device or run genymotion
- start appium 
- gwi clean runAppiumTest

**Comment by Shellyhan** [comment]
Hi I just tried running with BrowserStack and it's working! That's great!
Will try to run with local device and Appium later and create some test cases with Spock framework.

Thank you a lot!

Shelly

**Comment by mueke** [comment]
cool. have fun. 
georg
